search/story/urls.py
from django.urls import path
from . import views

app_name='story'

urlpatterns = [
     path('', views.story_list, name='story_list'),
     path('<slug:category_slug>', views.story_list, name='story_by_category'),
     path('<int:id>/', views.story_detail, name='story_detail'),
     path('search/',views.search,name='search'),

   # path('admin/', admin.site.urls),

]

search/story/views.py
from django.shortcuts import render,get_object_or_404
from .models import  Category,Story
from django.db.models import Q

# Create your views here.
def story_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    story = Story.objects.all()
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        story = story.filter(category=category)
    return render(request, 'story_list.html', {'categories':categories,
                                              'category':category,
                                              'story':story,
                                              })

def story_detail(request,id):
    story=get_object_or_404(Story,id=id)
    return render(request,'story_detail.html',{'story':story})

def search(request):
    query=None
    results=[]
    if request.method=="GET":
        query=request.GET.get('search')
        results=Story.objects.filter(Q(title__icontains=query) | Q(body__icontains=query) | Q(footer__icontains=query) )
    return  render(request,'search.html',{'query': query,
                                          'results': results})

search/story/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<script>

</script>



<body>
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
           <h3>
           {% with results.count as total_results %}
           Found {{ total_results }} result{{ total_results|pluralize }}
           {% endwith %}
           </h3>
   {% for c in results %}
   <a href="{{c.get_absolute_url}}"><h3>{{c.title}}</h3></a>
    <h3>{{c.footer}}</h3>


   {% empty %}
   <h4>There are no results for your query.</h4>
   {% endfor %}

{% else %}
    <h2>NO QUERY  ERROR </h2>
{% endif %}
</body>

search/story/templates/story_detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{{story.title}}</title>
  </head>
  <script>

</script>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <span class="navbar-brand mb-0 h1 ">B learning club</span>
    </nav>
  <div class="container">
    <main id = "">
   
    <h2 class="text-center"> {{story.title}}</h2> <hr>
    <p class="lead">{{story.body}} </p>
  </main>
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

search/story/templates/story_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<script>

</script>



<body>
    <nav class="navbar navbar-dark bg-primary">
        <span class="navbar-brand mb-0 h1 ">B learning club</span>
      </nav>

<div class="container">
<div class="" id="sidebar">
<h3>Categories</h3>
    <ul>
        <li>
        <h4> <a href="{% url "story:story_list" %}">All</a></h4>
        </li>
    {% for c in categories %}
        <li>
       <h4> <a href="{{ c.get_absolute_url }}">{{ c.name }}</a></h4>
        </li>
    {% endfor %}
    </ul>
</div>
<hr>
<div>
    <form action="{% url 'story:search' %}" class="form-inline" method="get">

        <div class="form-group mb-2">
            <h1>{% if category %}{{ category.name }}{% else %} STORIES {% endif %}</h1>
        </div>
        <div class="form-group mx-sm-3 mb-2">
        <label for="" class="sr-only">search</label>
        <input name="search" type="" class="form-control" id="" placeholder="type for search">
        </div>
      <button type="submit" class="btn btn-primary btn-lg mb-2">search</button>
    </form>

    <main id='story'>
    {% for x in story %}
     <h3> <a href="{{ x.get_absolute_url }}">{{x.title}}</a></h3>
     <p class="lead">{{x.footer}}</p>
     <hr>
    {% endfor %}
    </main>


</div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>